apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-managed-disk
  namespace: postgresdb
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 5Gi